'use strict';
const express = require('express');
const router = express.Router();
const Ctrl = require('../Controllers/CountriesController');
const { requireLogin, requirePermission, requireSuperAdmin } = require('../Middlewares/auth');
router.use(requireLogin, requireSuperAdmin);
router.get('/autocomplete',             Ctrl.autocomplete);
router.get('/',                        requirePermission('view_countries'),   Ctrl.index);
router.post('/paginate',               requirePermission('view_countries'),   Ctrl.paginate);
router.get('/export',                  requirePermission('export_countries'), Ctrl.exportData);
router.post('/export',                 requirePermission('export_countries'), Ctrl.exportData);
router.post('/import',                 requirePermission('import_countries'), Ctrl.importData);
router.post('/import/single',          requirePermission('import_countries'), Ctrl.importSingleRow);
router.post('/bulk-action',            requirePermission('edit_countries'),   Ctrl.bulkAction);
router.get('/create',                  requirePermission('add_countries'),    Ctrl.create);
router.post('/',                       requirePermission('add_countries'),    Ctrl.store);
router.get('/:uuid/usage',            requirePermission('view_countries'),   Ctrl.usage);
router.get('/:uuid/view-data',        requirePermission('view_countries'),   Ctrl.viewData);
router.get('/:uuid/edit',             requirePermission('edit_countries'),   Ctrl.edit);
router.post('/:uuid',                 requirePermission('edit_countries'),   Ctrl.update);
router.post('/:uuid/toggle-status',   requirePermission('edit_countries'),   Ctrl.toggleStatus);
router.post('/:uuid/recover',         requirePermission('edit_countries'),   Ctrl.recover);
router.post('/:uuid/delete',          requirePermission('delete_countries'), Ctrl.destroy);
module.exports = router;